from Analex.Analex import Analex
from Reader.reader import Reader
from Tokens.Tokens import Tokens, Token

class Parser:

    def __init__(self, Reader):
        self.analex= Analex(Reader)
        self.analex.analex()
        self.result = "" 
        self.name = "Generated by MELI"
        self.theme = "normal"
        self.codigo()

    
    def isValid(self):
        return self.analex.TK.tokenType in Tokens.tkns

    def codigo(self):
        if self.isValid():
            self.sentencia()
            self.codigo()
    
    def sentencia(self):
        tk = self.analex.TK.tokenType;
        if tk == Tokens.TXT :
            self.text()
        if tk == Tokens.BSL : #incluye name theme nwline etc
            self.set()
        if tk == Tokens.BOX :
            self.box("box")
        if tk == Tokens.ROW :
            self.box("row")
        if tk == Tokens.TLE:
            self.title()
        if tk == Tokens.LNK:
            self.link()
        if tk == Tokens.BTN:
            self.button()
        if tk == Tokens.IMG:
            self.imagen()


    def text(self):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                temp=f"<span>{self.analex.TK.value}</span>\n"
                self.analex.analex()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.result+=temp
                    self.analex.analex()
                else:
                    print("ERROR: Se esperaba )")
            else:
                print("ERROR: Se esperaba una cadena")
        else:
            print("ERROR: Se esperaba (")
    def set(self):
        self.analex.analex()
        tk = self.analex.TK.tokenType
        if tk == Tokens.NAM:
            self.analex.analex()
            tk = self.analex.TK.tokenType
            if tk == Tokens.CAD:
                self.name = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR: Se esperaba una cadena")
        elif tk == Tokens.NLN: 
            self.analex.analex()
            self.result+="<br>\n"
        elif tk == Tokens.THM:
            self.analex.analex()
            tk = self.analex.TK.tokenType
            if tk == Tokens.CAD:
                self.theme= self.analex.TK.value;
                self.analex.analex()
            else:
                print("ERROR se esperaba un tema")

    def box(self, type):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.result+=f"<div class='{type}'>\n"
            self.analex.analex()
            self.sentencia()
            self.moreSent()
            if self.analex.TK.tokenType == Tokens.PCI:
                self.result+="</div>\n"
                self.analex.analex()
            else:
                print("ERROR se esperaba )")
        else:
            print("ERROR se esperaba (")
    def moreSent(self):
        if self.analex.TK.tokenType == Tokens.COM:
            self.analex.analex()
            self.sentencia()
            self.moreSent()
    def title(self):
        self.analex.analex()
        tempSize = 1
        if self.analex.TK.tokenType == Tokens.NUM:
            tempSize = int(self.analex.TK.value);
            self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                self.result+=f"<h{tempSize}>{self.analex.TK.value}</h{tempSize}>\n"
                self.analex.analex()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.analex.analex()
                else:
                    print("ERROR(title) se esperaba )")
            else:
                print("ERROR(title) se esperaba un STRING")
        else:
            print("ERROR(title) se esperaba (")

    def link(self):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            alt = ""
            href = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                alt = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una Comma")
                exit(1)
            if self.analex.TK.tokenType == Tokens.CAD:
                href = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una CADENA")
                exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba )")
                exit(1)
            self.result+=f"<a href={href}>{alt}</a>\n"
        else:
            print("ERROR(title) se esperaba (")
    def button(self):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            alt = ""
            action = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                alt = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una Comma")
                exit(1)
            if self.analex.TK.tokenType == Tokens.CAD:
                action= self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una CADENA")
                exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba )")
                exit(1)
            self.result+=f'<button onclick="{action.replace('"',"'")}">{alt}</button>\n'
        else:
            print("ERROR(title) se esperaba (")
    
    def imagen(self):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            css = ""
            ruta = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                ruta = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una Comma")
                exit(1)
            if self.analex.TK.tokenType == Tokens.CAD:
                css= self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una CADENA")
                exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba )")
                exit(1)
            self.result+=f'<img src="{ruta}" style="{css.replace('\"', '\'')}">\n'
        else:
            print("ERROR(title) se esperaba (")

    def getResult(self):
        return f"""<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{self.name}</title>
        <link rel="stylesheet" href="css/{self.theme}.css">
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>

{self.result}

        <br>
        <span>powered by M.E.L.I. preAlpha 0.0.1 </span>
    </body>
</html>"""

