from Analex.Analex import Analex
from Reader.reader import Reader
from Tokens.Tokens import Tokens, Token

class Parser:

    def __init__(self, Reader):
        self.analex= Analex(Reader)
        self.analex.analex()
        self.result = "" 
        self.name = "Generated by MELI"
        self.theme = "normal"
        self.codigo()

    
    def isValid(self):
        return self.analex.TK.tokenType in Tokens.tkns

    def codigo(self):
        if self.isValid():
            self.sentencia()
            self.codigo()
    
    def sentencia(self):
        tk = self.analex.TK.tokenType;
        if tk == Tokens.TXT :
            self.text()
        if tk == Tokens.BSL : #incluye name theme nwline etc
            self.set()
        if tk == Tokens.BOX :
            self.box("box")
        if tk == Tokens.ROW :
            self.box("row")
        if tk == Tokens.TLE:
            self.title()
        if tk == Tokens.LNK:
            self.link()
        if tk == Tokens.BTN:
            self.button()
        if tk == Tokens.IMG:
            self.imagen()
        if tk == Tokens.INP:
            self.input()
        if tk == Tokens.LST:
            self.list()
        if tk == Tokens.TBL:
            self.table()
    def modifier(self):
        mod = ""
        while self.analex.TK.tokenType != Tokens.PAP:
            if self.analex.TK.tokenType == Tokens.ID_:
                mod += f' id="{self.analex.TK.value}"'
                self.analex.analex()
            elif self.analex.TK.tokenType == Tokens.CLS:
                mod += f' class="{self.analex.TK.value}"'
                self.analex.analex()
        return mod
    def text(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                temp=f"<span{mod}>{self.analex.TK.value}</span>\n"
                self.analex.analex()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.result+=temp
                    self.analex.analex()
                else:
                    print("ERROR: Se esperaba )")
            else:
                print("ERROR: Se esperaba una cadena")
        else:
            print("ERROR: Se esperaba (")
    def set(self):
        self.analex.analex()
        tk = self.analex.TK.tokenType
        if tk == Tokens.NAM:
            self.analex.analex()
            tk = self.analex.TK.tokenType
            if tk == Tokens.CAD:
                self.name = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR: Se esperaba una cadena")
        elif tk == Tokens.NLN: 
            self.analex.analex()
            self.result+="<br>\n"
        elif tk == Tokens.THM:
            self.analex.analex()
            tk = self.analex.TK.tokenType
            if tk == Tokens.CAD:
                self.theme= self.analex.TK.value;
                self.analex.analex()
            else:
                print("ERROR se esperaba un tema")

    def box(self, type):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.result+=f"<div class='{type}'{mod}>\n"
            self.analex.analex()
            self.sentencia()
            self.moreSent()
            if self.analex.TK.tokenType == Tokens.PCI:
                self.result+="</div>\n"
                self.analex.analex()
            else:
                print("ERROR se esperaba )")
        else:
            print("ERROR se esperaba (")
    def moreSent(self):
        if self.analex.TK.tokenType == Tokens.COM:
            self.analex.analex()
            self.sentencia()
            self.moreSent()
    def title(self):
        self.analex.analex()
        tempSize = 1
        if self.analex.TK.tokenType == Tokens.NUM:
            tempSize = int(self.analex.TK.value);
            self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                self.result+=f"<h{tempSize}{mod}>{self.analex.TK.value}</h{tempSize}>\n"
                self.analex.analex()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.analex.analex()
                else:
                    print("ERROR(title) se esperaba )")
            else:
                print("ERROR(title) se esperaba un STRING")
        else:
            print("ERROR(title) se esperaba (")

    def link(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            alt = ""
            href = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                alt = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una Comma")
                exit(1)
            if self.analex.TK.tokenType == Tokens.CAD:
                href = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una CADENA")
                exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba )")
                exit(1)
            self.result+=f"<a href={href} {mod}>{alt}</a>\n"
        else:
            print("ERROR(title) se esperaba (")
    def button(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            alt = ""
            action = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                alt = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una Comma")
                exit(1)
            if self.analex.TK.tokenType == Tokens.CAD:
                action= self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba una CADENA")
                exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(link) Se esperaba )")
                exit(1)
            self.result+=f'<button onclick="{action.replace('"',"'")}"{mod}>{alt}</button>\n'
        else:
            print("ERROR(title) se esperaba (")
    
    def imagen(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            css = ""
            ruta = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                ruta = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(image) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
            else:
                print("ERROR(image) Se esperaba una Comma")
                exit(1)
            if self.analex.TK.tokenType == Tokens.CAD:
                css= self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR(image) Se esperaba una CADENA")
                exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(image) Se esperaba )")
                exit(1)
            self.result+=f'<img src="{ruta}" style="{css.replace('\"', '\'')}"{mod}/>\n'
        else:
            print("ERROR(image) se esperaba (")
    
    def input(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            placeholder = ""
            type = ""
            if self.analex.TK.tokenType == Tokens.CAD:
                type= self.analex.TK.value
                self.analex.analex()

            else:
                print("ERROR(input) Se esperaba un STRING")
                exit(1)
            if self.analex.TK.tokenType == Tokens.COM:
                self.analex.analex()
                if self.analex.TK.tokenType == Tokens.CAD:
                    placeholder = self.analex.TK.value
                    self.analex.analex()
                else:
                    print("ERROR(input) Se esperaba una CADENA")
                    exit(1)
            if self.analex.TK.tokenType == Tokens.PCI:
                self.analex.analex()
            else:
                print("ERROR(input) Se esperaba )")
                exit(1)
            label = f'<label for="input">  {placeholder}  </label>' if placeholder!="" else ""
            self.result+=f'<div class="input-container"><input type="{type}"{mod}/>{label}</div>\n'
        else:
            print("ERROR(title) se esperaba (")
    
    def list(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                element= self.analex.TK.value
                self.analex.analex()
                more = self.moreList()
                self.result+=f'<ul{mod}>\n<li>{element}</li>\n{more}</ul>'
                self.analex.analex()
    
    def moreList(self):
        if self.analex.TK.tokenType == Tokens.COM:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                element= self.analex.TK.value
                self.analex.analex()
                more = self.moreList()
                result=f'<li>{element}</li>\n{more}'
                return result
        else:
            return ""
    
    def table(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.result+=f'<table{mod}>\n'
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.ROW:
                self.tableRow()
                self.tableMoreRow()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.result+='</table>\n'
                    self.analex.analex()
                else:
                    print("ERROR(table) se esperaba )")
            else:
                print("ERROR(table) se esperaba row()")

    def tableRow(self):
        self.analex.analex()
        mod = self.modifier()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            self.result += f"<tr{mod}>\n"
            if self.analex.TK.tokenType == Tokens.CAD:
                self.result += f"<td>{self.analex.TK.value}</td>\n"
                self.analex.analex()
                self.moreCad()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.analex.analex()
                    self.result += f"</tr>\n"
                else:
                    print("ERROR(table, row) se esperaba )")


    def tableMoreRow(self):
        if self.analex.TK.tokenType == Tokens.COM:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.ROW:
                self.tableRow()
                self.tableMoreRow()
            else:
                print("ERROR(table, row) se esperaba row()")

    def moreCad(self):
        if self.analex.TK.tokenType == Tokens.COM:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                self.result += f"<td>{self.analex.TK.value}</td>"
                self.analex.analex()
                self.moreCad()
            else:
                print("ERROR(table, row) se esperaba un STRING")
        
    def getResult(self):
        return f"""<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{self.name}</title>
        <link rel="stylesheet" href="css/{self.theme}.css">
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>

{self.result}

        <br>
        <div class="watermark">powered by M.E.L.I. v1.0.0</div>
    </body>
</html>"""

