from Analex.Analex import Analex
from Reader.reader import Reader
from Tokens.Tokens import Tokens, Token

class Parser:

    def __init__(self, Reader):
        self.analex= Analex(Reader)
        self.analex.analex()
        self.result = "" 
        self.name = "Generated by MELI"
        self.theme = "normal"
        self.codigo()

    
    def isValid(self):
        return self.analex.TK.tokenType in Tokens.tkns

    def codigo(self):
        self.analex.TK.printTK()
        if self.isValid():
            self.sentencia()
            self.codigo()
    
    def sentencia(self):
        tk = self.analex.TK.tokenType;
        if tk == Tokens.TXT :
            self.text()
        if tk == Tokens.BSL :
            self.set()
        if tk == Tokens.BOX :
            self.box("box")
        if tk == Tokens.ROW :
            self.box("row")


    def text(self):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.analex.analex()
            if self.analex.TK.tokenType == Tokens.CAD:
                temp=f"<span>{self.analex.TK.value}</span>\n "
                self.analex.analex()
                if self.analex.TK.tokenType == Tokens.PCI:
                    self.result+=temp
                    self.analex.analex()
                else:
                    print("ERROR: Se esperaba )")
            else:
                print("ERROR: Se esperaba una cadena")
        else:
            print("ERROR: Se esperaba (")
    def set(self):
        self.analex.analex()
        tk = self.analex.TK.tokenType
        if tk == Tokens.NAM:
            self.analex.analex()
            tk = self.analex.TK.tokenType
            if tk == Tokens.CAD:
                self.name = self.analex.TK.value
                self.analex.analex()
            else:
                print("ERROR: Se esperaba una cadena")
        elif tk == Tokens.NLN: 
            self.analex.analex()
            self.result+="<br>"
        elif tk == Tokens.THM:
            self.analex.analex()
            tk = self.analex.TK.tokenType
            if tk == Tokens.CAD:
                self.theme= self.analex.TK.value;
                self.analex.analex()
            else:
                print("ERROR se esperaba un tema")

    def box(self, type):
        self.analex.analex()
        if self.analex.TK.tokenType == Tokens.PAP:
            self.result+=f"<div class='{type}'>\n"
            self.analex.analex()
            self.sentencia()
            self.moreSent()
            if self.analex.TK.tokenType == Tokens.PCI:
                self.result+="</div>\n"
                self.analex.analex()
            else:
                print("ERROR se esperaba )")
        else:
            print("ERROR se esperaba (")
    def moreSent(self):
        if self.analex.TK.tokenType == Tokens.COM:
            self.analex.analex()
            self.sentencia()
            self.moreSent()
        else:
            pass

    






    def getResult(self):
        return f"""<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{self.name}</title>
        <link rel="stylesheet" href="css/{self.theme}.css">
        <link rel="stylesheet" href="css/style.css">
    </head>
    <body>
        {self.result}
        <br>
        <span>powered by M.E.L.I. preAlpha 0.0.1 </span>
    </body>
</html>"""

